---
title: "Homework 7: Mapping"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, eval = TRUE)
library(tidyverse)
library(lubridate)
```

### Overview

This assignment is to be done in pairs and started in class. That means that you should be pushing essentially the same work to both of your personal repos. Do be sure to note the name of your teammate at the top of your homework.


### A Portland Map

Your assignment is to create a single map of the city of Portland that visualizes at least two spatial data sets. Your choice of data shouldn't be arbitrary; it should lead to a map that tells a specific story or answers a specific question. In addition to constructing the map, write one paragraph that describes why you selected the data that you did, and what we can learn from the map.

Some considerations:

- A trove of spatial data related to Portland can be found at: https://gis-pdx.opendata.arcgis.com/.
- You'll find data in several formats. We covered just one in class (shapefiles), but you're welcome to work with others as long as the spatial integrity is maintained.
- Be careful with projections and datums. It's important that these match between your data sets and basemap.
- Experiment with the aesthetics of the ``ggmap`` - there are lots of options to customize it.



